"""Generate a compile-time weight-offset header for the SYNTHESISABLE top.

decoder.hpp addresses weights by std::string name -- fine for csim, not
synthesisable. The Vitis kernel needs the offsets as constants (or a BRAM
table). This emits hls/src/weight_offsets.hpp: one TOff per (role, layer),
zero-filled where a role doesn't apply to a layer type.

  python3 scripts/gen_offsets.py
"""

import json
import os

MANIFEST = "artifacts/qwen35_int8.manifest.json"
OUT = "hls/src/weight_offsets.hpp"

ROLES = {
    "input_layernorm.weight": "W_IN_LN",
    "post_attention_layernorm.weight": "W_POST_LN",
    "linear_attn.in_proj_qkv.weight": "W_QKV",
    "linear_attn.in_proj_z.weight": "W_Z",
    "linear_attn.in_proj_b.weight": "W_B",
    "linear_attn.in_proj_a.weight": "W_A",
    "linear_attn.conv1d.weight": "W_CONV",
    "linear_attn.A_log": "W_ALOG",
    "linear_attn.dt_bias": "W_DTB",
    "linear_attn.norm.weight": "W_LNORM",
    "linear_attn.out_proj.weight": "W_OUTP",
    "self_attn.q_proj.weight": "W_QP",
    "self_attn.k_proj.weight": "W_KP",
    "self_attn.v_proj.weight": "W_VP",
    "self_attn.q_norm.weight": "W_QN",
    "self_attn.k_norm.weight": "W_KN",
    "self_attn.o_proj.weight": "W_OP",
    "mlp.gate_proj.weight": "W_GATE",
    "mlp.up_proj.weight": "W_UP",
    "mlp.down_proj.weight": "W_DOWN",
}

m = json.load(open(MANIFEST))
by_name = {t["name"]: t for t in m["tensors"]}

# per-role [24] tables, zero-initialised
tables = {r: [None] * 24 for r in ROLES.values()}
singles = {}

for t in m["tensors"]:
    n = t["name"]
    if n == "embed_tokens.weight":
        singles["W_EMBED"] = t
    elif n == "norm.weight":
        singles["W_FINAL"] = t
    else:
        assert n.startswith("layers.")
        layer = int(n.split(".")[1])
        role = n.split(".", 2)[2]
        tables[ROLES[role]][layer] = t


def toff(t):
    if t is None:
        return "{0,0,0,0,0}"
    sh = t["shape"]
    out = sh[0] if len(sh) >= 1 else 0
    inn = sh[1] if len(sh) >= 2 else 0
    dt = 1 if t["dtype"] == "int8" else 0
    so = t.get("scale_offset", 0)
    return f"{{{t['offset']},{so},{out},{inn},{dt}}}"


os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("// GENERATED by scripts/gen_offsets.py -- do not edit.\n")
    f.write("// Compile-time weight offsets into the packed HBM blob, for the\n")
    f.write("// synthesisable top (no std::string). Regenerate if pack_weights changes.\n")
    f.write("#pragma once\n#include <cstdint>\nnamespace qwen {\n\n")
    f.write("struct TOff { uint64_t off, soff; int out, in, dtype; };\n\n")
    for name, t in singles.items():
        f.write(f"static const TOff {name} = {toff(t)};\n")
    f.write("\n")
    for role, arr in tables.items():
        body = ", ".join(toff(x) for x in arr)
        f.write(f"static const TOff {role}[24] = {{{body}}};\n")
    f.write("\n}  // namespace qwen\n")

print(f"wrote {OUT}: {len(singles)} singletons + {len(tables)} role tables x24")
